export const HOME_ROUTE = '/'
export const LOGIN_ROUTE = '/login'
export const SCHOOL_ROUTE = '/school-table'
export const USER_ROUTE = '/user-table'
export const PROFILE_ROUTE = '/profile'
export const FORM_ROUTE ='/form'
